name: Integration
on: [push]
jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: setup.py
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -e ".[dev]"
      - name: Run format check
        run: black --diff --color --check .
      - name: Run type check
        run: mypy --install-types --non-interactive .
      - name: Create release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release version --changelog --commit --push --vcs-release --skip-build
